#!/bin/bash
# Quick Conversion Script for Mobile to Desktop Layout
# This script lists all screens that need conversion

echo "=== Screens Requiring Desktop Layout Conversion ==="
echo ""
echo "Priority 1 - Main Navigation (8 screens):"
echo "  1. FamilyOverviewScreen.tsx"
echo "  2. PatientDashboard.tsx"
echo "  3. DoctorHomeDashboard.tsx"
echo "  4. PatientProfileScreen.tsx"
echo "  5. PedigreeBuilderScreen.tsx"
echo "  6. PatientResultsScreen.tsx"
echo "  7. DoctorSettingsScreen.tsx"
echo "  8. VisualPedigreeAnalysisScreen.tsx"
echo ""
echo "Priority 2 - Analysis Screens (12 screens):"
echo "  9. AutosomalDominantScreen.tsx"
echo "  10. AutosomalRecessiveScreen.tsx"
echo "  11. XLinkedScreen.tsx"
echo "  12. YLinkedScreen.tsx"
echo "  13. MitochondrialScreen.tsx"
echo "  14. InheritanceDetectionScreen.tsx"
echo "  15. RuleBasedEvaluationScreen.tsx"
echo "  16. ConfidenceScoreScreen.tsx"
echo "  17. PredictionResultScreen.tsx"
echo "  18. DNAReportAnalysisScreen.tsx"
echo "  19. PedigreeAnalysisListScreen.tsx"
echo "  20. DoctorNotesScreen.tsx"
echo ""
echo "Priority 3 - Doctor Tools (14 screens):"
echo "  21. PatientDetailViewScreen.tsx"
echo "  22. GenerateReportScreen.tsx"
echo "  23. ExportReportScreen.tsx"
echo "  24. ShareReportScreen.tsx"
echo "  25. MedicalCredentialsScreen.tsx"
echo "  26. SpecializationScreen.tsx"
echo "  27. AnalysisPreferencesScreen.tsx"
echo "  28. ConsultationScheduleScreen.tsx"
echo "  29. CaseNotesScreen.tsx"
echo "  30. ContinuingEducationScreen.tsx"
echo "  31. ProfessionalNetworkScreen.tsx"
echo "  32. ComplianceScreen.tsx"
echo "  33. ReportPatientListScreen.tsx"
echo "  34. PatientInheritanceReportScreen.tsx"
echo ""
echo "Priority 4 - Pedigree Management (6 screens):"
echo "  35. SavePedigreeScreen.tsx"
echo "  36. UpdatePedigreeScreen.tsx"
echo "  37. SubmitPedigreeScreen.tsx"
echo "  38. DeleteConfirmationScreen.tsx"
echo "  39. CompareChangesScreen.tsx"
echo "  40. VersionHistoryScreen.tsx"
echo ""
echo "Priority 5 - Settings & Support (4 screens):"
echo "  41. LanguageScreen.tsx"
echo "  42. FAQScreen.tsx"
echo "  43. FeedbackScreen.tsx"
echo "  44. EducationalContentScreen.tsx"
echo ""
echo "Priority 6 - Auth/Onboarding (9 screens):"
echo "  45. WelcomeScreen.tsx"
echo "  46. RoleSelectionScreen.tsx"
echo "  47. OTPVerificationScreen.tsx"
echo "  48. ForgotPasswordScreen.tsx"
echo "  49. ResetPasswordScreen.tsx"
echo "  50. ProfileSetupScreen.tsx"
echo "  51. PrivacyConsentScreen.tsx"
echo "  52. DashboardSelectionScreen.tsx"
echo "  53. LoginScreen.tsx (has LoginPage too)"
echo "  54. SignUpScreen.tsx (has SignUpPage too)"
echo ""
echo "Keep As-Is (Full Screen - 3 screens):"
echo "  - SplashScreen.tsx (startup animation)"
echo "  - ProcessingScreen.tsx (loading animation)"
echo "  - LogoutScreen.tsx (goodbye screen)"
echo ""
echo "TOTAL: 54 screens to convert + 3 to keep = 57 screens"
echo "Already converted: 11 screens"
echo "=== Grand Total: 68 screens ===" 
